name: Build And Publish Image To Quay.io
on: 
  push:
    branches: [master, dev*]
env:
  REGISTRY: quay.io
  QUAY_NAMESPACE: overbaard
  QUAY_IMAGE_NAME: ob-ci-action-tooling
jobs:
  build-and-publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      ####################################################
      # Some pre-checking and setting of variables
      - id: check
        name: Check relevant branch
        run: |
          repo_owner=${{ github.repository_owner }}
          ref=${{ github.ref }}
    
          build=0
          version=
          
          echo Pushed to branch ${ref}
          echo Repository owner ${repo_owner}
          
          if [[ "${repo_owner}" == 'overbaard' ]]; then
            echo Push to upstream. Checking branch....
            
            if [[ "${ref}" != 'refs/heads/master' ]]; then
              # In the upstream repository we only build if we pushed to the 'master' branch
              # and the docker tag should be 'latest'
              echo We should build from the ${ref} branch
              build=1
              version=latest
            fi
          elif [[ "${repo_owner}" == 'kabir' ]]; then
            echo Push to ${repo_owner}. Checking branch....
            
            if [[ "${ref}" != 'refs/heads/master' ]]; then
              # In the forks we only build if we did not push to the 'master' branch.
              # The branches triggering all this are set in the on/push/branches of the
              # workflow as a whole.
              # The docker tag should be 'dev'
              echo We should build from the ${ref} branch
              build=1
              version=dev
            fi
          else
            echo Push to ${repo_owner}. We will not perform a build.
          fi
          
          if [[ ${build} -eq 1 ]]; then
            echo Checking settings for pushing to quay.io...
            
            # Check secrets for pushing to Quay.io and set build var correspondingly
            # Checking these directly with the expressions fails the job if not set
            # so go via env vars
            username=${{secrets.QUAY_USERNAME}}
            token=${{secrets.QUAY_TOKEN}}
            if [[ -n ${username} && -n ${token} ]]; then
              echo Settings found!
            else
              echo Settings not found.
              build=0
            fi
          fi
          
          if [[ ${build} -eq 1 ]]; then
            echo "Setting BUILD output variable"
            echo ::set-output name=BUILD::${build}
            echo "VERSION=${version}" >> $GITHUB_ENV

          fi

      ####################################################
      # Java/Quarkus stuff to build a native executable
      - uses: actions/checkout@v2
        if: ${{ steps.check.outputs.BUILD }}
      
      - uses: actions/cache@v2
        if: ${{ steps.check.outputs.BUILD }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - uses: actions/setup-java@v1
        if: ${{ steps.check.outputs.BUILD }}
        with:
          java-version: 11

      - name: Build Native Executable
        if: ${{ steps.check.outputs.BUILD }}
        run: |
          mvn -B install -Dnative


      ####################################################
      # Docker stuff
      - name: Prepare Output Variables For Docker Push
        id: docker-tag
        if: ${{ steps.check.outputs.BUILD }}
        run: |
          TMP=${REGISTRY}/${QUAY_NAMESPACE}/${QUAY_IMAGE_NAME}:${VERSION}
          echo ::set-output name=TAG::${TMP}

      - name: Check Docker Tag
        if: ${{ steps.check.outputs.BUILD }}
        run: echo ${{ steps.docker-tag.outputs.TAG }}

      - name: Set up QEMU
        if: ${{ steps.check.outputs.BUILD }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.BUILD }}
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        if: ${{ steps.check.outputs.BUILD }}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.docker-tag.outputs.TAG }}